### ISSUE TITLE
DOC: function args, kwargs, and class arguments badly need documenting

### ISSUE THREAD

**Issue by dohmatob** [tansey/pycfr#4]
Though it took me only a few moments to figure out what the code was doing,

![classes_poker](https://cloud.githubusercontent.com/assets/634068/5578059/a417b490-901f-11e4-9462-ec0610db1b66.png)

it'd be good to have minimal documentation for function args (max_bets, holecards, etc.) and class attributes (I'm not talking about pep*, who cares :) ). This can be done progressively.

**Comment by tansey** [comment]
I'd certainly welcome better documentation. :)
