### ISSUE TITLE
Game tree logic is not very DRY: GameTree and PublicTree, possible code duplication ?

### ISSUE THREAD

**Issue by dohmatob** [tansey/pycfr#6]
There seems to be a huge code duplication between PublicTree and its mother Gametree class. Also, this sub-classing looks like over-abstraction; Ideally, you'd have a single object class that implements the game tree logic (lest I'm missing something here). What do you think ?

**Comment by tansey** [comment]
A GameTree is different than a PublicTree. I think the abstraction is fine and helps form conceptual differences between the two. There are some subtle differences between the two and it's important to keep them separate, particularly when it comes to different CFR variants.

**Comment by dohmatob** [comment]
Fine. Then a one-line docstring  per class and/or more informative class
names would be useful :)

OK, I'll continue the dev on my own fork https://github.com/dohmatob/pycfr,
since we have a number of divergences in point-of-view and use-case. For
the moment, the main added value of this fork is my quick-and-dirty
implementation of sequence-form representation
http://www.maths.lse.ac.uk/personal/stengel/TEXTE/geb1996a.pdf (a
representation which is linear in the size of the game tree), the goal
being to attack the resulting saddle-point problems (for Nash Equilibria,
best-responses, etc.) with formal methods (unpublished WIP).

In future, I'll (re-)propose my fork for a merge.

Keep up the good work!

Cheers

On Wed, Dec 31, 2014 at 4:08 PM, Wesley Tansey notifications@github.com
wrote:

> A GameTree is different than a PublicTree. I think the abstraction is fine
> and helps form conceptual differences between the two. There are some
> subtle differences between the two and it's important to keep them
> separate, particularly when it comes to different CFR variants.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tansey/pycfr/issues/6#issuecomment-68446920.

## 

DED
